# Correlated multivariate normal

In [2]:
import numpy as np

In [3]:
sig_v = np.array([2, 5, 2])
cor_m = np.array([[1, 0.7, -0.2], [0.7, 1, 0.5], [-0.2, 0.5, 1]])
print(sig_v, '\n', cor_m)

[2 5 2] 
 [[ 1.   0.7 -0.2]
 [ 0.7  1.   0.5]
 [-0.2  0.5  1. ]]


In [4]:
# Vector * Vector(Matrix * Matrix): Component-wise
print(sig_v * sig_v, '\n')
print(cor_m * cor_m, '\n')

# Matrix x Vector ??: component-wise in each vector
print( cor_m * sig_v, '\n')
print( sig_v * cor_m, '\n') # Same

[ 4 25  4] 

[[ 1.    0.49  0.04]
 [ 0.49  1.    0.25]
 [ 0.04  0.25  1.  ]] 

[[ 2.   3.5 -0.4]
 [ 1.4  5.   1. ]
 [-0.4  2.5  2. ]] 

[[ 2.   3.5 -0.4]
 [ 1.4  5.   1. ]
 [-0.4  2.5  2. ]] 



In [5]:
# Dot(inner) product
print( np.dot(sig_v, sig_v) )
print( sig_v.dot(sig_v) ) # same

33
33


In [6]:
# Matrix multiplication ?
print(np.matmul(cor_m, cor_m), '\n')

print(np.matmul(cor_m, sig_v), '\n')  # sig_v is treated as a column vector

print(np.matmul(sig_v, cor_m)) # sig_v is treated as a row vector

[[ 1.53  1.3  -0.05]
 [ 1.3   1.74  0.86]
 [-0.05  0.86  1.29]] 

[ 5.1  7.4  4.1] 

[ 5.1  7.4  4.1]


In [7]:
# Exciplicitly make a column vector
print( np.reshape(sig_v,(3,1)) )
#print( sig_v.reshape((3,1)) )
#sig_v.transpose() # same

[[2]
 [5]
 [2]]


In [8]:
cov_m = sig_v * cor_m * np.reshape(sig_v,(3,1))
print(cov_m)

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]]


In [9]:
# Cholesky decomposition of covariance matrix

chol_m = np.linalg.cholesky(cov_m)
print(chol_m)

[[ 2.          0.          0.        ]
 [ 3.5         3.57071421  0.        ]
 [-0.4         1.79235851  0.79211803]]


In [10]:
# Let's verify that C x C^T = Covariance

print( chol_m @ chol_m.transpose(), '\n' )
print( chol_m @ chol_m.transpose() - cov_m )

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]] 

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [11]:
# Now let's create multivariate normal random variables following the covariance matrix

# First, create standard normals (1000x3)

znorm_m = np.random.normal(size=(3, 10000))
znorm_m

array([[ 0.61295147, -0.73042392, -0.09696316, ..., -0.10503082,
        -1.38387442, -0.911016  ],
       [ 0.37007179, -0.10504174, -1.52577411, ...,  0.07904194,
        -1.60315902, -0.89872176],
       [-1.0276226 ,  1.48083121,  0.58050482, ...,  0.8934943 ,
         0.96597255, -1.58429734]])

In [13]:
# Then multiply C^T

#xnorm_m = znorm_m @ chol_m.transpose()
xnorm_m = chol_m @ znorm_m
xnorm_m

array([[  1.22590294,  -1.46084784,  -0.19392632, ...,  -0.21006163,
         -2.76774883,  -1.82203199],
       [  3.46675073,  -2.93155776,  -5.78747435, ...,  -0.08537168,
        -10.56798317,  -6.39763455],
       [ -0.39587767,   1.27689022,  -2.2361206 , ...,   0.89143677,
         -1.55472167,  -2.50137569]])

In [14]:
# Let's verify that X = C * Z  follows the covariance

cov_m_sample = np.cov( xnorm_m )
print( 'Cov from sample:\n', cov_m_sample )
print( 'Error:\n', cov_m_sample - cov_m )

Cov from sample:
 [[  3.95075338   6.88686292  -0.81091698]
 [  6.88686292  24.87156734   5.10535661]
 [ -0.81091698   5.10535661   4.0869234 ]]
Error:
 [[-0.04924662 -0.11313708 -0.01091698]
 [-0.11313708 -0.12843266  0.10535661]
 [-0.01091698  0.10535661  0.0869234 ]]


In [16]:
# also check the correation

cor_m_sample = np.corrcoef( xnorm_m )
print( 'Cov from sample:\n', cor_m_sample )
print( 'Error:\n', cor_m_sample - cor_m )

Cov from sample:
 [[ 1.          0.69475215 -0.20180791]
 [ 0.69475215  1.          0.50637967]
 [-0.20180791  0.50637967  1.        ]]
Error:
 [[ 0.         -0.00524785 -0.00180791]
 [-0.00524785  0.          0.00637967]
 [-0.00180791  0.00637967  0.        ]]
