# Correlated multivariate normal

In [1]:
import numpy as np

In [33]:
sig_v = np.array([2, 5, 2])
cor_m = np.array([[1, 0.7, -0.2], [0.7, 1, 0.5], [-0.2, 0.5, 1]])
cor_m

array([[ 1. ,  0.7, -0.2],
       [ 0.7,  1. ,  0.5],
       [-0.2,  0.5,  1. ]])

In [47]:
# Vector * Vector(Matrix * Matrix): Component-wise
print(sig_v * sig_v, '\n')
print(cor_m * cor_m, '\n')

# Matrix x Vector ??: component-wise in each vector
print( cor_m * sig_v, '\n')
print( sig_v * cor_m, '\n') # Same

[ 4 25  4] 

[[ 1.    0.49  0.04]
 [ 0.49  1.    0.25]
 [ 0.04  0.25  1.  ]] 

[[ 2.   3.5 -0.4]
 [ 1.4  5.   1. ]
 [-0.4  2.5  2. ]] 

[[ 2.   3.5 -0.4]
 [ 1.4  5.   1. ]
 [-0.4  2.5  2. ]] 



In [38]:
# Dot(inner) product
print( np.dot(sig_v, sig_v) )
print( sig_v.dot(sig_v) ) # same

33
33


In [43]:
# Matrix multiplication ?
print(np.matmul(cor_m, cor_m), '\n')

print(np.matmul(cor_m, sig_v), '\n')  # sig_v is treated as a column vector

print(np.matmul(sig_v, cor_m)) # sig_v is treated as a row vector

[[ 1.53  1.3  -0.05]
 [ 1.3   1.74  0.86]
 [-0.05  0.86  1.29]] 

[ 5.1  7.4  4.1] 

[ 5.1  7.4  4.1]


In [58]:
# Exciplicitly make a column vector
print( np.reshape(sig_v,(3,1)) )
#print( sig_v.reshape((3,1)) )

[[2]
 [5]
 [2]]


In [65]:
cov_m = sig_v * cor_m * np.reshape(sig_v,(3,1))
print(cov_m)

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]]


In [75]:
chol_m = np.linalg.cholesky(cov_m)
print(chol_m)

[[ 2.          0.          0.        ]
 [ 3.5         3.57071421  0.        ]
 [-0.4         1.79235851  0.79211803]]


In [76]:
print( np.matmul( chol_m, chol_m.transpose() ) )
np.matmul( chol_m, chol_m.transpose() ) - cov_m

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]]


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])